"""
Script para atualizar cargos e gestores dos colaboradores
baseado na planilha Excel fornecida
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app import create_app
from app.models import db, User, JobPosition, user_managers
from datetime import datetime, timezone
from sqlalchemy import text

app = create_app()

# Dados extraídos da planilha Excel
# Formato: (NOME_COLABORADOR, DATA, RESPONSAVEL, CARGO)
dados_planilha = [
    ("ADRIANA SILGUEIRO DOS REIS", "01/11/2021", "FERNANDA JURADO", "AUTONOMO (Gerente Administrativo)"),
    ("DANILO SIQUEIRA DA PAIXAO SILVA", "16/02/2024", "MARIO SAPERE NETO", "GERENTE ADMINISTRATIVO"),
    ("ADRIANA ALVES SILVA VIANA", "16/02/2024", "DANILO SIQUEIRA DA PAIXAO SILVA", "GERENTE OPERACIONAL"),
    ("ADRIANO FRANCISCO DE JESUS PAULA", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("AMANDA FREITAS MACHADO", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("ANA LUCIA DE ARAUJO", "16/02/2024", "RENATA LUCIANO SANTOS URZEDO", "AUXILIAR DE LABORATORIO"),
    ("APARECIDA DE SOUZA NERY", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ASSISTENTE ADMINISTRATIVO"),
    ("CAMILA ARAUJO BORGES", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("CLAUDIO SANTA ROSA FILHO", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE IMOBILIZACAO ORTOPEDICA"),
    ("CLEIDE DOS SANTOS SILVA", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("CLEIDE TOMAZ DE FREITAS LIMA", "16/02/2024", "RENATA LUCIANO SANTOS URZEDO", "BIOQUÍMICO"),
    ("CLEONICE RIBEIRO BARBOSA PAULO", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE IMOBILIZACAO ORTOPEDICA"),
    ("CLEUMA GIRICI MATOS", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("CEUZA RIBEIRO DA SILVA OLIVEIRA", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("DIRLENE AMARA XAVIER", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("EULINA LUCIA DIAS", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("ELISANIA APARECIDA FREITAS BALSAMAO", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("FERNANDA FREITAS COELHO", "16/02/2024", "PATRICIA FLAUZINO DA CUNHA", "FARMACEUTICO"),
    ("FERNANDA ROCHA DE OLIVEIRA", "16/02/2024", "PATRICIA FLAUZINO DA CUNHA", "AUXILIAR DE FARMACIA"),
    ("FLAVIA REGINA FERREIRA", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("GABRIEL AUGUSTOS ALVES OLIVEIRA", "16/02/2024", "DANILO SIQUEIRA DA PAIXAO SILVA", "ENCARREGADO DE MANUTENÇÃO"),
    ("GELIS FERREIRA ALVES", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("GEOVANA FERREIRA MORAIS", "16/02/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR ADMINISTRATIVO"),
    ("GEOVANNA FREITAS", "16/02/2024", "ADRIANA ALVES SILVA VIANA", "MAQUEIRO"),
    ("GUILHERME RODRIGUES SANTOS", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "MAQUEIRO"),
    ("HIVALDA GONCALVES FERREIRA", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("ISILIDA ALICE SANCHES DOS SANTOS", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("JUCIHEI SILVA MORAIS", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "MAQUEIRO"),
    ("JOANA DARC PEREIRA BARBOSA", "16/02/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR ADMINISTRATIVO"),
    ("JOCEMARA ROCHA SEABRA", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("KEILA NEVES BORGES", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("LEIA FREITAS MARQUES", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "FISIOTERAPEUTA"),
    ("LORRAN HERNANDES SOUZA", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "MAQUEIRO"),
    ("LUANA DIAS DOS SANTOS", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("LUZIA QUIRINO DE ALMEIDA", "16/02/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE LAVANDERIA"),
    ("MARIA LACIA DOS SANTOS", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("MARIELE FREITAS PEREIRA", "16/02/2024", "JOSE CRISTIANO DA SILVA", "TECNICO DE SEGURANCA NO TRABALHO JR"),
    ("NAYLA FELICIO AMARAL", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("MICHELE PEREIRA DOS SANTOS FIEL", "16/02/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR ADMINISTRATIVO"),
    ("NATALIA FABIANA FREITAS FONSECA", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("NUBIA LILIAN RODRIGUES DOS REIS", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("PAMMELA SUELLEN SOARES BORGES", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("PATRICIA DE FREITAS OLIVEIRA", "16/02/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR ADMINISTRATIVO"),
    ("PAULA FERNANDA SANTOS", "16/02/2024", "DANILO SIQUEIRA DA PAIXAO SILVA", "COORDENADOR DE HUMANIZACAO"),
    ("RAFAEL ANDRADE FREITAS FARIA", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "MAQUEIRO"),
    ("RAFAELA MARIA SILVA RODRIGUES", "16/02/2024", "PATRICIA FLAUZINO DA CUNHA", "AUXILIAR ADMINISTRATIVO"),
    ("RENATA LUCIANO SANTOS URZEDO", "16/02/2024", "DANILO SIQUEIRA DA PAIXAO SILVA", "LIDER DE LABORATORIO"),
    ("RODRIGO SOARES", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "INSTRUMENTADOR CIRURGICO"),
    ("ROSANGELA APARECIDA DOS SANTOS", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("RYAN DE CHRISTHAN SANCHES SILVA", "16/02/2024", "RENATA LUCIANO SANTOS URZEDO", "AUXILIAR DE LABORATORIO"),
    ("SILVANE APARECIDA DE SOUZA", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("SIMONE ALVES DE LIMA", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("SOLANGE FERNANDES SILVA", "16/02/2024", "PAULA FERNANDA SANTOS", "ASSISTENTE SOCIAL"),
    ("SONIA APARECIDA OLIVEIRA QUEIROZ", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("SONIA ROSA DA SILVA MEDEIROS", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("SUELY DA SILVA SANTOS", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("TASSIA RAIANE NERES RODRIGUES", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("THAIS PEREIRA DA SILVA", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("THAISA ROCHA", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("WALDECY DA GRACA DE FREITAS", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("WELLINGTON DO NASCIMENTO FELIX", "16/02/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("SOBREIA APARECIDA DA SILVA", "18/03/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TEC.IMOBILIZACAO ORT"),
    ("ALINE DAIANY DE PAULA", "18/03/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("EDINA MARIA SILVA DOS SANTOS", "18/03/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("DIANA MIRANDA SALVADOR", "18/03/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("ANA FLAVIA SALVADOR DOS SANTOS", "18/03/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("RAILAD DA TOMAZ DE ALMEIDA", "18/03/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("LEANDRO SILVA", "18/03/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TEC.IMOBILIZACAO ORT"),
    ("CRISTIANO DA ROCHA SANTOS DANTAS", "18/03/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("JOAO LAZARO DA SILVA SANTOS", "01/04/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE LAVANDERIA"),
    ("IONICA FERREIRA", "01/04/2024", "ADRIANA ALVES SILVA VIANA", "TECNICO DE ENFERMAGEM"),
    ("ANA PAULA FERREIRA FRANCO", "01/04/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("LEANDRA MARTINS TIAGO", "04/04/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("GEFANIO VIEIRA BOTELHO", "04/04/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("CAMILA SANTA ROSA", "01/04/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR ADMINISTRATIVO"),
    ("ELAINE BORGES DA SILVA OLIVEIRA", "02/04/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
    ("ROSINEI FERREIRA BARBOSA", "04/04/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
    ("LUANA OLIVEIRA SILVA", "04/04/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
    ("APARECIDA ALINE IDENUSA", "04/04/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
    ("EVELINE FERREIRA DA SILVA PEREIRA", "04/04/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
    ("JESHLAINE VIEIRA LOPES DA SILVA", "04/04/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
    ("MANOELINA BENEDITA DE SOUZA", "04/04/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
    ("ROSANA APARECIDA ARAUJO SILVA", "04/04/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
    ("SUELEN APARECIDA RIBEIRO SANTIAGO BARBOSA", "04/04/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
    ("MARIA DE FATIMA FERNANDES SILVA", "04/04/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
    ("MARIO HERMES APARECIDO TEIXEIRA", "04/04/2024", "ADRIANA ALVES SILVA VIANA", "JARDINEIRO"),
    ("VANESSA LENE REZENDE DE MATOS", "06/05/2024", "DANILO SIQUEIRA DA PAIXAO SILVA", "DENTISTA"),
    ("MARIANA TEIXEIRA ERCOLANO", "06/05/2024", "SABRINA DA SILVA BENETTI", "ENFERMEIRO DA QUALIDADE"),
    ("VALQUIRIA SANTOS ROCHA", "06/05/2024", "PATRICIA FLAUZINO DA CUNHA", "ANALISTA ADMINISTRATIVO PL"),
    ("ANA CAROLINE FERNANDES PEREIRA", "08/04/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR ADMINISTRATIVO"),
    ("NAZA MANDELA VISCONDI BISPO", "13/05/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("AURELIA CARVALHO NUNES", "10/06/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR ADMINISTRATIVO"),
    ("JESSICA MAIA ANDRADE", "01/07/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("IZABELA FREITAS BICALHO", "01/07/2024", "RENATA LUCIANO SANTOS URZEDO", "AUXILIAR DE LABORATORIO"),
    ("MAYRA APARECIDA OLIVEIRA SILVEIRA", "02/07/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "INSTRUMENTADOR CIRURGICO"),
    ("GABRIELA KAROLINY SOUZA DE FREITAS", "05/08/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("ALEXANDRA SILVA DE SOUZA", "05/08/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("SAMANDA AMERICA DE SOUZA", "02/08/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("MAYANY DIAS URZEDO", "05/08/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("ADRIANA SILVA MARTINS", "13/08/2024", "PATRICIA FLAUZINO DA CUNHA", "FARMACEUTICO"),
    ("MARCIA REGINA DA SILVA LUCAS", "19/08/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE FATURAMENTO"),
    ("MICHELI LEITE DA SILVA", "29/08/2024", "RENATA LUCIANO SANTOS URZEDO", "AUXILIAR DE LABORATORIO"),
    ("PAULA DA SILVA", "07/10/2024", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("FLAVIO ALBERTO MOISES", "07/10/2024", "GABRIEL AUGUSTOS ALVES OLIVEIRA", "AJUDANTE DE MANUTENÇÃO"),
    ("MIRIAM CARLA DE SOUZA SANTOS", "01/11/2024", "RENATA LUCIANO SANTOS URZEDO", "BIOMÉDICO"),
    ("JULIANA FERREIRA SOLER", "22/12/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
    ("APARECIDA DE MELO", "16/12/2024", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
    ("LUCIÉNIA OLIVEIRA DA SILVA", "20/01/2025", "DANILO SIQUEIRA DA PAIXAO SILVA", "COORDENADOR DE ENFERMAGEM"),
    ("KELLIN CRISTYNA SILVA OLIVEIRA", "20/01/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("ANA CAROLINA FREITAS SILVA", "20/01/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("WELDA ALVES DA SILVA", "20/01/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("MARIELY SILVA PEREIRA SANTOS", "20/01/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("MARINA CRISTINA FERREIRA", "20/01/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("LAIRYS LARA FREITAS GARCIA", "10/02/2025", "RENATA LUCIANO SANTOS URZEDO", "BIOMÉDICO"),
    ("MARCO TULIO FERREIRA SOUZA", "10/02/2025", "ADRIANA ALVES SILVA VIANA", "AUXILIAR ADMINISTRATIVO"),
    ("NEUSA CANDIDA DE OLIVEIRA", "10/02/2025", "ADRIANA ALVES SILVA VIANA", "AUXILIAR ADMINISTRATIVO"),
    ("RITA DE CASSIA FERRAZ PYANTE", "20/02/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("MURILO ALVES BARBOSA MENEZES", "21/02/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("GIOVANNA QUEIROZ BORGES SEVERINO", "17/03/2025", "DANILO SIQUEIRA DA PAIXAO SILVA", "AUXILIAR ADMINISTRATIVO"),
    ("PATRICIA FLAUZINO DA CUNHA", "24/03/2025", "DANILO SIQUEIRA DA PAIXAO SILVA", "COORDENADOR DE SUPRIMENTOS"),
    ("MARIA AUXILIADORA AMARAL PACHECO", "22/04/2025", "ADRIANA ALVES SILVA VIANA", "TECNICO DE ENFERMAGEM"),
    ("LUCIMEIRE LOUZADA MONTALVAO", "04/04/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("NEI ALVES BARBOSA JUNIOR", "22/04/2025", "LUIZA PROCÓPIO DE CARVALHO", "GERENTE ASSISTENCIAL"),
    ("GEOVANNA CATALAO GIOVANNI", "28/04/2025", "RENATA LUCIANO SANTOS URZEDO", "TECNICO DE ENFERMAGEM"),
    ("LUCIÉNIA DIVINA DE FREITAS", "05/05/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "AUXILIAR DE HIGIENIZACAO"),
    ("JEAN CARLOS PEREIRA DE SOUZA", "05/05/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "MAQUEIRO"),
    ("LUCAS MORAES ARAUJO", "19/05/2025", "DANILO SIQUEIRA DA PAIXAO SILVA", "ANALISTA DE T.I PL"),
    ("TATILA WALDERLÂNDIA DOS SANTOS FERREIRA", "16/05/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("ANA GABRIELLA ALMEIDA MARRAS", "02/05/2025", "ADRIANA ALVES SILVA VIANA", "AUXILIAR ADMINISTRATIVO"),
    ("ISADORA CRISTINA PEREIRA SOUZA", "22/06/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "ENFERMEIRO"),
    ("DILMA FERNANDA FERREIRA SANTOS", "01/07/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("ANEZIO JUNIOR MEDEIROS DA SILVA", "01/07/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("TALITA CRISTINA FREITAS DA SILVA", "02/07/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "AUXILIAR DE HIGIENIZACAO"),
    ("DORVALINA ALVES DE OLIVEIRA DE SOUZA", "02/07/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "AUXILIAR DE HIGIENIZACAO"),
    ("EDINILVA ROSA DOS SANTOS", "07/07/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("FLAVIO ALBERTO MOISES JUNIOR", "07/07/2025", "PATRICIA FLAUZINO DA CUNHA", "AUXILIAR DE ALMOXARIFADO"),
    ("DESIRRE ALMEIDA FREITAS DELLA TORRE", "21/07/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("REGINALDO JOSE DE FREITAS", "11/08/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("JONATAS CARLOS OLIVEIRA", "11/08/2025", "DANILO SIQUEIRA DA PAIXAO SILVA", "PSICÓLOGO"),
    ("ESTEFANE ARAUJO DE FREITAS BERNINI", "11/08/2025", "ADRIANA ALVES SILVA VIANA", "AUXILIAR ADMINISTRATIVO"),
    ("LESELI GALDINO ARAUJO", "11/08/2025", "GABRIEL AUGUSTOS ALVES OLIVEIRA", "OFICIAL ELÉTRICA"),
    ("JOSIANE SANTOS PESCHIETTI", "18/08/2025", "ADRIANA ALVES SILVA VIANA", "MAQUEIRO"),
    ("REGINA FREITAS DA COSTA", "18/08/2025", "ADRIANA ALVES SILVA VIANA", "AUXILIAR ADMINISTRATIVO"),
    ("MAGDA BEATRIZ RIBEIRO DA SILVA", "09/08/2025", "LILIAN VALDINEIA DA CUNHA", "ANALISTA DE RH JR"),
    ("RENATA SILVA SAMARINO", "11/08/2025", "RENATA LUCIANO SANTOS URZEDO", "AUXILIAR DE LABORATORIO"),
    ("MARILEIA FARIA DINIZ", "11/08/2025", "PATRICIA FLAUZINO DA CUNHA", "AUXILIAR DE FARMACIA"),
    ("MARIA EDUARDA SOARES MARQUES", "22/09/2025", "DANILO SIQUEIRA DA PAIXAO SILVA", "APRENDIZ"),
    ("GABRIELE MAGELA ESTEVAN", "22/09/2025", "DANILO SIQUEIRA DA PAIXAO SILVA", "APRENDIZ"),
    ("MELISSA MELO DA SILVA", "22/09/2025", "DANILO SIQUEIRA DA PAIXAO SILVA", "TECNICO DE ENFERMAGEM"),
    ("ADRIANE GOMES SILVA", "10/06/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("JOAO LUCAS BENICIO JUSTINO", "06/10/2025", "LUCIÉNIA OLIVEIRA DA SILVA", "TECNICO DE ENFERMAGEM"),
    ("CARLOS EDUARDO FONSECA DA SILVA", "06/10/2025", "GABRIEL AUGUSTOS ALVES OLIVEIRA", "TECNICO DE REFRIGERAÇÃO"),
    ("PEDRO SILVA", "18/11/2025", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
    ("MARIA DO SOCORRO SILVA DOS SANTOS", "03/11/2025", "ADRIANA ALVES SILVA VIANA", "AUXILIAR DE HIGIENIZACAO"),
]

def normalizar_nome(nome):
    """Normaliza nome para comparação (remove acentos, maiúsculas, espaços extras)"""
    import unicodedata
    if not nome:
        return ""
    # Normalizar unicode
    nome = unicodedata.normalize('NFKD', nome)
    # Remover acentos
    nome = ''.join(c for c in nome if not unicodedata.combining(c))
    # Converter para maiúsculas e remover espaços extras
    return ' '.join(nome.upper().split())

def encontrar_usuario_por_nome(nome_planilha, usuarios):
    """Tenta encontrar um usuário pelo nome"""
    nome_norm = normalizar_nome(nome_planilha)
    
    for user in usuarios:
        user_nome_norm = normalizar_nome(user.name)
        
        # Match exato
        if user_nome_norm == nome_norm:
            return user
        
        # Match parcial (primeiro e último nome)
        partes_planilha = nome_norm.split()
        partes_user = user_nome_norm.split()
        
        if len(partes_planilha) >= 2 and len(partes_user) >= 2:
            # Primeiro e último nome iguais
            if partes_planilha[0] == partes_user[0] and partes_planilha[-1] == partes_user[-1]:
                return user
    
    return None

def encontrar_cargo_por_nome(nome_cargo, cargos):
    """Tenta encontrar um cargo pelo nome"""
    nome_norm = normalizar_nome(nome_cargo)
    
    # Limpar o nome do cargo (remover parênteses e conteúdo)
    if '(' in nome_norm:
        nome_norm = nome_norm.split('(')[0].strip()
    
    for cargo in cargos:
        cargo_nome_norm = normalizar_nome(cargo.name)
        
        if cargo_nome_norm == nome_norm:
            return cargo
            
        # Match parcial
        if nome_norm in cargo_nome_norm or cargo_nome_norm in nome_norm:
            return cargo
    
    return None

def atualizar_usuarios():
    """Atualiza cargos e gestores dos usuários"""
    with app.app_context():
        # Buscar todos os usuários e cargos
        usuarios = User.query.all()
        cargos = JobPosition.query.all()
        
        print(f"\n{'='*60}")
        print(f"ATUALIZANDO CARGOS E GESTORES DOS USUÁRIOS")
        print(f"{'='*60}")
        print(f"Total de usuários no sistema: {len(usuarios)}")
        print(f"Total de cargos cadastrados: {len(cargos)}")
        print(f"Total de registros na planilha: {len(dados_planilha)}")
        print(f"{'='*60}\n")
        
        atualizados_cargo = 0
        atualizados_gestor = 0
        nao_encontrados = []
        cargos_nao_encontrados = set()
        gestores_nao_encontrados = set()
        
        # Primeiro, criar um mapa de usuários por nome normalizado
        mapa_usuarios = {}
        for user in usuarios:
            nome_norm = normalizar_nome(user.name)
            mapa_usuarios[nome_norm] = user
        
        for nome_colaborador, data, responsavel, cargo in dados_planilha:
            # Encontrar o colaborador
            usuario = encontrar_usuario_por_nome(nome_colaborador, usuarios)
            
            if not usuario:
                nao_encontrados.append(nome_colaborador)
                continue
            
            # Atualizar cargo
            cargo_obj = encontrar_cargo_por_nome(cargo, cargos)
            if cargo_obj:
                if usuario.job_position_id != cargo_obj.id:
                    usuario.job_position_id = cargo_obj.id
                    atualizados_cargo += 1
                    print(f"✓ Cargo: {usuario.name} → {cargo_obj.name}")
            else:
                cargos_nao_encontrados.add(cargo)
            
            # Encontrar e atribuir gestor
            gestor = encontrar_usuario_por_nome(responsavel, usuarios)
            if gestor and gestor.id != usuario.id:
                # Verificar se o gestor já está atribuído
                gestores_atuais = [m.id for m in usuario.assigned_managers]
                if gestor.id not in gestores_atuais:
                    # Adicionar gestor
                    db.session.execute(
                        user_managers.insert().values(
                            employee_id=usuario.id,
                            manager_id=gestor.id,
                            assigned_at=datetime.now(timezone.utc),
                            assigned_by_id=1  # Admin
                        )
                    )
                    atualizados_gestor += 1
                    print(f"✓ Gestor: {usuario.name} ← {gestor.name}")
            else:
                if not gestor:
                    gestores_nao_encontrados.add(responsavel)
        
        # Commit das alterações
        db.session.commit()
        
        # Relatório final
        print(f"\n{'='*60}")
        print(f"RELATÓRIO FINAL")
        print(f"{'='*60}")
        print(f"Cargos atualizados: {atualizados_cargo}")
        print(f"Gestores atribuídos: {atualizados_gestor}")
        print(f"Colaboradores não encontrados: {len(nao_encontrados)}")
        
        if nao_encontrados:
            print(f"\n⚠ Colaboradores não encontrados no sistema:")
            for nome in nao_encontrados[:20]:  # Mostrar só os primeiros 20
                print(f"   - {nome}")
            if len(nao_encontrados) > 20:
                print(f"   ... e mais {len(nao_encontrados) - 20}")
        
        if cargos_nao_encontrados:
            print(f"\n⚠ Cargos não encontrados:")
            for cargo in cargos_nao_encontrados:
                print(f"   - {cargo}")
        
        if gestores_nao_encontrados:
            print(f"\n⚠ Gestores não encontrados:")
            for gestor in gestores_nao_encontrados:
                print(f"   - {gestor}")
        
        print(f"\n{'='*60}")
        print("Atualização concluída!")
        print(f"{'='*60}\n")

if __name__ == "__main__":
    atualizar_usuarios()
